"use client";
import { useEffect, useState } from "react";

type Lang = "en" | "ar";
const copy = {
 en: { nav:["Treatments","Concerns","Specialists","Results","About"], book:"Book appointment", eyebrow:"HM Facial Aesthetics Clinic", hero:"Healthier You.\nBrighter Tomorrow.", intro:"Advanced aesthetic, skin and hair treatments tailored to you.", explore:"Explore treatments", consult:"Book a consultation", concerns:"What would you like to improve?", concernSub:"Begin with what matters to you.", signature:"Signature treatments", statement:"Our goal is to help you be\nthe best version of yourself.", results:"Real results", resultsSub:"Demo imagery only. Every treatment plan begins with a consultation.", specialists:"Meet our specialists", cta:"Your consultation starts here.", location:"Muscat · Al Khoud · Al Barakat Street", close:"Close menu", all:"All" },
 ar: { nav:["العلاجات","الاهتمامات","الأخصائيون","النتائج","عن العيادة"], book:"احجز موعداً", eyebrow:"عيادة HM لجمال الوجه", hero:"صحة أفضل لك.\nغدٌ أكثر إشراقاً.", intro:"علاجات متقدمة للبشرة والشعر والجمال، مصممة بعناية لتناسبك.", explore:"اكتشف العلاجات", consult:"احجز استشارة", concerns:"ما الذي تودين تحسينه؟", concernSub:"نبدأ بما يهمك أنت.", signature:"علاجاتنا المميزة", statement:"هدفنا أن نساعدك لتكوني\nأفضل نسخة من نفسك.", results:"نتائج حقيقية", resultsSub:"صور توضيحية للنموذج فقط. تبدأ كل خطة علاج باستشارة.", specialists:"تعرفي على أخصائيينا", cta:"استشارتك تبدأ من هنا.", location:"مسقط · الخوض · شارع البركات", close:"إغلاق القائمة", all:"الكل" }
};
const concerns = [
 ["Skin","البشرة","Pigmentation · Acne · Texture","التصبغات · حب الشباب · الملمس","/images/skin-consultation.png"],
 ["Face","الوجه","Botox · Fillers · Contouring","بوتوكس · فيلر · نحت الوجه","/images/face-consultation.png"],
 ["Hair","الشعر","Hair loss · Transplant · PRP","تساقط الشعر · زراعة · بلازما","/images/hair-consultation.png"],
 ["Laser","الليزر","Hair removal · Carbon laser","إزالة الشعر · ليزر كربوني","/images/laser-treatment.png"],
 ["Body","الجسم","Contouring · Tightening · Slimming","نحت · شد · تنحيف","/images/body-contouring.png"]
];
const treatments = [["Lip enhancement","تعزيز الشفاه","/images/face-consultation.png"],["Skin brightening","إشراقة البشرة","/images/skin-consultation.png"],["Hair restoration","استعادة الشعر","/images/hair-consultation.png"],["Carbon laser","ليزر الكربون","/images/laser-treatment.png"]];
export default function Home() {
 const [lang,setLang]=useState<Lang>("en"), [menu,setMenu]=useState(false), [booking,setBooking]=useState(false); const t=copy[lang];
 useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr";document.querySelectorAll<HTMLImageElement>('img[src^="/images/"]').forEach(image=>{image.src=`/HM-clinic${image.getAttribute("src")}`})},[lang]);
 return <main className={lang==="ar"?"arabic":""}>
 <header className="header"><a className="logo" href="#top">HM <span>FACIAL AESTHETICS</span></a><nav>{t.nav.map((n,i)=><a key={n} href={["#treatments","#concerns","#specialists","#results","#about"][i]}>{n}</a>)}</nav><div className="nav-actions"><button className="lang" onClick={()=>setLang(lang==="en"?"ar":"en")}>{lang==="en"?"AR":"EN"}</button><button className="button small" onClick={()=>setBooking(true)}>{t.book}</button><button className="menu-btn" aria-label="Open menu" onClick={()=>setMenu(!menu)}>☰</button></div></header>
 {menu&&<div className="mobile-menu"><button onClick={()=>setMenu(false)}>× {t.close}</button>{t.nav.map(n=><a key={n} href="#concerns" onClick={()=>setMenu(false)}>{n}</a>)}<a className="button" href="#book">{t.book}</a></div>}
 <section className="hero" id="top"><div className="hero-image"/><div className="hero-copy"><p className="eyebrow">{t.eyebrow}</p><h1>{t.hero.split("\n").map(x=><span key={x}>{x}</span>)}</h1><p className="lede">{t.intro}</p><div className="hero-actions"><a className="button" href="#treatments">{t.explore} <b>↗</b></a><button className="text-link ghost" onClick={()=>setBooking(true)}>{t.consult} <b>→</b></button></div></div><p className="hero-note">MUSCAT, OMAN<br/>23° 37′ N</p></section>
 <section className="section" id="concerns"><div className="section-title"><p className="eyebrow">{t.concernSub}</p><h2>{t.concerns}</h2></div><div className="concerns">{concerns.map(([en,ar,desEn,desAr,img])=><a className="concern" href="#treatments" key={en}><img src={img} alt=""/><div><h3>{lang==="en"?en:ar}</h3><p>{lang==="en"?desEn:desAr}</p><span>↗</span></div></a>)}</div></section>
 <section className="section treatments" id="treatments"><div className="section-title side"><div><p className="eyebrow">HM EDIT</p><h2>{t.signature}</h2></div><a className="text-link" href="/treatments/skin-brightening">{t.explore} →</a></div><div className="treatment-grid">{treatments.map(([en,ar,img],i)=>{const slug=["lip-enhancement","skin-brightening","hair-restoration","carbon-laser"][i];return <article className={'treatment t'+i} key={en}><img src={img} alt={lang==="en"?en:ar}/><div><p className="eyebrow">{i===0?"FACIAL AESTHETICS":i===1?"SKIN & DERMATOLOGY":i===2?"HAIR":"LASER"}</p><h3>{lang==="en"?en:ar}</h3><a href={`/treatments/${slug}`}>{lang==="en"?"Discover":"اكتشفي"} <b>→</b></a></div></article>})}</div></section>
 <section className="feature"><div className="feature-img"/><div className="feature-copy"><p className="eyebrow">SKIN & DERMATOLOGY</p><h2>{lang==="en"?"A brighter way\nto care for skin.":"طريقة أكثر إشراقاً\nللعناية بالبشرة."}</h2><p>{lang==="en"?"Our Skin Brightening Protocol is designed to reduce the appearance of pigmentation and promote a more even-looking complexion.":"بروتوكول إشراقة البشرة مصمم لتخفيف مظهر التصبغات وتعزيز مظهر بشرة أكثر تجانساً."}</p><div className="areas">{(lang==="en"?["Face","Dark areas","Elbows","Knees"]:["الوجه","المناطق الداكنة","الأكواع","الركب"]).map(x=><span key={x}>{x}</span>)}</div><a href="#book" className="button light">{lang==="en"?"Discover treatment":"اكتشفي العلاج"} ↗</a></div></section>
 <section className="section results" id="results"><div className="section-title"><p className="eyebrow">CLINICAL APPROACH</p><h2>{lang==="en"?"A considered consultation.":"استشارة مدروسة."}</h2><p>{lang==="en"?"Every plan starts with a careful consultation and a detailed skin analysis.":"تبدأ كل خطة باستشارة دقيقة وتحليل مفصل للبشرة."}</p></div><div className="comparison"><div className="before"><span>{lang==="en"?"CONSULTATION SETUP":"تجهيز الاستشارة"}</span></div><div className="after"><span>{lang==="en"?"SKIN ANALYSIS":"تحليل البشرة"}</span></div><div className="slider"><i/></div></div></section>
 <section className="section doctors" id="specialists"><div className="section-title"><p className="eyebrow">THE HM TEAM</p><h2>{t.specialists}</h2></div><div className="doctor-grid">{["Dr. Maya Al-Harthy","Dr. Leila Khan","Dr. Nour Ibrahim"].map((name,i)=><article className="doctor" key={name}><img src={["/images/face-consultation.png","/images/hair-consultation.png","/images/laser-treatment.png"][i]} alt="Clinic equipment and treatment environment"/><p className="eyebrow">MOCK PROFILE</p><h3>{name}</h3><p>{lang==="en"?["Aesthetic medicine","Skin & laser specialist","Facial aesthetics"][i]:["طب تجميلي","أخصائية البشرة والليزر","جماليات الوجه"][i]}</p><a className="text-link" href={`/doctors/${["maya-al-harthy","leila-khan","nour-ibrahim"][i]}`}>{lang==="en"?"View profile":"عرض الملف"} →</a></article>)}</div></section>
 <section className="statement" id="about"><p className="eyebrow">OUR PHILOSOPHY</p><h2>{t.statement.split("\n").map(x=><span key={x}>{x}</span>)}</h2></section>
 <section className="book" id="book"><p className="eyebrow">HM FACIAL AESTHETICS CLINIC</p><h2>{t.cta}</h2><button className="button light" onClick={()=>setBooking(true)}>{t.book} ↗</button><div><p>{t.location}</p><a href="tel:79944450">79944450</a><a href="tel:79944460">79944460</a></div></section>
 <footer><a className="logo" href="#top">HM <span>FACIAL AESTHETICS</span></a><p>© 2026 HM Facial Aesthetics Clinic</p><button className="lang" onClick={()=>setLang(lang==="en"?"ar":"en")}>{lang==="en"?"العربية":"English"}</button></footer>
 {booking&&<BookingModal lang={lang} onClose={()=>setBooking(false)}/>} 
 </main>
}

function BookingModal({lang,onClose}:{lang:Lang,onClose:()=>void}){
 const [step,setStep]=useState(0),[choice,setChoice]=useState("Consultation"),[sent,setSent]=useState(false);
 const ar=lang==="ar"; const labels=ar?["نوع الموعد","الاهتمام","الخدمة","الأخصائي","التاريخ والوقت","بياناتك"]:["Appointment type","Your concern","Service","Specialist","Date & time","Your details"];
 const options=[ar?["استشارة","علاج"]:["Consultation","Treatment"],ar?["البشرة","الوجه والحقن","الشعر","الليزر","الجسم"]:["Skin","Face & injectables","Hair","Laser","Body"],ar?["استشارة البشرة","إشراقة البشرة","بوتوكس","ليزر الكربون"]:["Skin consultation","Skin brightening","Botox","Carbon laser"],ar?["د. مايا الحارثي","د. ليلى خان","د. نور إبراهيم"]:["Dr. Maya Al-Harthy","Dr. Leila Khan","Dr. Nour Ibrahim"],ar?["الأحد، 21 سبتمبر · 4:00 م","الاثنين، 22 سبتمبر · 5:30 م","الثلاثاء، 23 سبتمبر · 6:15 م"]:["Sun, 21 Sep · 4:00 PM","Mon, 22 Sep · 5:30 PM","Tue, 23 Sep · 6:15 PM"]];
 if(sent)return <div className="modal-backdrop"><section className="booking-modal confirmation"><button className="close" onClick={onClose}>×</button><p className="eyebrow">HM FACIAL AESTHETICS</p><h2>{ar?"تم استلام طلبك.":"You’re on the list."}</h2><p>{ar?"هذا نموذج تجريبي فقط — لم يتم إرسال أي بيانات. سيتواصل فريق HM لتأكيد الموعد.":"This is a prototype only — no information was sent. The HM team would confirm your appointment shortly."}</p><button className="button" onClick={onClose}>{ar?"إغلاق":"Close"}</button></section></div>;
 return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Appointment booking"><section className="booking-modal"><button className="close" onClick={onClose} aria-label="Close booking">×</button><div className="booking-side"><p className="eyebrow">HM FACIAL AESTHETICS</p><h2>{ar?"احجزي وقتاً لك.":"Make time for you."}</h2><p>{ar?"سيأخذ الأمر أقل من دقيقتين. هذه تجربة حجز تجريبية فقط.":"It takes less than two minutes. This is a front-end booking prototype only."}</p><div className="steps">{labels.map((x,i)=><span className={i===step?"current":i<step?"done":""} key={x}>{String(i+1).padStart(2,"0")} <i>{x}</i></span>)}</div></div><div className="booking-main"><p className="step-count">{ar?`الخطوة ${step+1} من 6`:`STEP ${step+1} OF 6`}</p><h3>{labels[step]}</h3>{step<5?<div className="booking-options">{options[step].map(x=><button className={choice===x?"selected":""} onClick={()=>{setChoice(x);setStep(current=>current+1)}} key={x}>{x}<b>→</b></button>)}</div>:<form onSubmit={e=>{e.preventDefault();setSent(true)}}><label>{ar?"الاسم الكامل":"Full name"}<input required placeholder={ar?"اكتبي اسمك":"Your name"}/></label><label>{ar?"رقم الهاتف":"Phone number"}<input required type="tel" placeholder="7994 4450"/></label><label>{ar?"البريد الإلكتروني":"Email"}<input required type="email" placeholder="you@example.com"/></label><label>{ar?"ملاحظات اختيارية":"Optional notes"}<textarea placeholder={ar?"كيف يمكننا مساعدتك؟":"How can we help?"}/></label><button className="button" type="submit">{ar?"إرسال الطلب":"Send request"} ↗</button></form>}<div className="booking-nav"><button disabled={step===0} onClick={()=>setStep(step-1)}>{ar?"السابق":"Back"}</button></div></div></section></div>
}
