import Link from "next/link";

export function generateStaticParams(){return ["lip-enhancement","skin-brightening","hair-restoration","carbon-laser"].map(slug=>({slug}));}

const data: Record<string,{title:string;category:string;description:string;helps:string[]}> = {
  "lip-enhancement": {title:"Lip enhancement",category:"Facial aesthetics",description:"A consultation-led approach to lip shape, balance and hydration. Your clinician will discuss suitability and a plan tailored to your goals.",helps:["Lip definition","Balanced proportions","Personalised aesthetic goals"]},
  "skin-brightening": {title:"Skin brightening",category:"Skin & dermatology",description:"A considered treatment plan designed to support a brighter, more even-looking complexion. Suitability is assessed in consultation.",helps:["Appearance of uneven tone","Visible pigmentation","Skin texture and radiance"]},
  "hair-restoration": {title:"Hair restoration",category:"Hair",description:"A personalised pathway for people concerned about hair thinning, density or hairline changes. Every recommendation starts with an assessment.",helps:["Hair thinning concerns","Hairline planning","Ongoing hair care"]},
  "carbon-laser": {title:"Carbon laser",category:"Laser",description:"A dermatologist-led laser option that may be discussed for concerns including skin texture and the appearance of excess oil.",helps:["Skin refresh","Texture concerns","A tailored skincare plan"]}
};
export default async function TreatmentPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const item=data[slug]??data["skin-brightening"];return <main className="detail-page"><header className="detail-header"><Link className="logo" href="/">HM <span>FACIAL AESTHETICS</span></Link><Link href="/#book" className="button small">Book appointment</Link></header><section className="detail-hero"><div><p className="eyebrow">{item.category.toUpperCase()}</p><h1>{item.title}</h1><p>{item.description}</p><Link className="button" href="/#book">Book a consultation ↗</Link></div><div className="detail-image"/></section><section className="detail-content"><div><p className="eyebrow">WHAT IT MAY HELP WITH</p><h2>Designed around you.</h2></div><ul>{item.helps.map(x=><li key={x}>{x}<span>→</span></li>)}</ul><div className="detail-note"><p className="eyebrow">CONSULTATION FIRST</p><p>Treatment suitability, details and any aftercare are discussed with your clinician. No outcomes are guaranteed.</p></div></section></main>}
